In [0]:
%tensorflow_version 1.x

In [0]:
import numpy as np
import tensorflow as tf

In [0]:
tf.enable_eager_execution()

In [0]:
X= np.array(
    [
     [0,0 ],
     [1,0],
     [1,1],
     [0,0],
     [0,1]
     ], dtype="float32"
)
X

array([[0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [0., 1.]], dtype=float32)

In [0]:
y=np.array([
            [1,0,0],
            [0,1,0],
            [0,0,1],
            [1,0,0],
            [0,0,1]
            ], dtype="float32")

y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [0]:
initializer=tf.contrib.layers.\
    xavier_initializer()

w0=tf.Variable(initializer([2,10]))
w0

<tf.Variable 'Variable:0' shape=(2, 10) dtype=float32, numpy=
array([[ 0.54333   ,  0.61780673,  0.25800395,  0.36719197, -0.4360658 ,
         0.39069742,  0.02562344, -0.45730948, -0.25460708,  0.25761014],
       [ 0.57655233, -0.54163605, -0.35785928,  0.2446987 , -0.1499821 ,
         0.6597329 , -0.31234893,  0.29235446,  0.6246814 ,  0.21096402]],
      dtype=float32)>

In [0]:
b0=tf.Variable(initializer([10]))
b0

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([-0.30458403,  0.1494788 ,  0.19349635, -0.48112452,  0.35617536,
       -0.16572082,  0.34867287, -0.09986541,  0.42840332,  0.5285728 ],
      dtype=float32)>

In [0]:
tf.matmul(X,w0)+b0

<tf.Tensor: id=38, shape=(5, 10), dtype=float32, numpy=
array([[-0.30458403,  0.1494788 ,  0.19349635, -0.48112452,  0.35617536,
        -0.16572082,  0.34867287, -0.09986541,  0.42840332,  0.5285728 ],
       [ 0.23874599,  0.7672855 ,  0.4515003 , -0.11393255, -0.07989043,
         0.2249766 ,  0.3742963 , -0.5571749 ,  0.17379624,  0.78618294],
       [ 0.8152983 ,  0.22564948,  0.09364101,  0.13076615, -0.22987252,
         0.8847095 ,  0.06194738, -0.26482043,  0.79847765,  0.99714696],
       [-0.30458403,  0.1494788 ,  0.19349635, -0.48112452,  0.35617536,
        -0.16572082,  0.34867287, -0.09986541,  0.42840332,  0.5285728 ],
       [ 0.2719683 , -0.39215726, -0.16436294, -0.23642582,  0.20619327,
         0.49401206,  0.03632393,  0.19248906,  1.0530847 ,  0.7395368 ]],
      dtype=float32)>

In [0]:
hypothesis0=tf.sigmoid(tf.matmul(X,w0)+b0)
hypothesis0

<tf.Tensor: id=44, shape=(5, 10), dtype=float32, numpy=
array([[0.42443728, 0.5373003 , 0.54822373, 0.38198662, 0.58811426,
        0.45866436, 0.5862957 , 0.47505438, 0.6054923 , 0.62915015],
       [0.5594046 , 0.6829334 , 0.6109959 , 0.47154763, 0.48003802,
        0.5560081 , 0.5924967 , 0.36420137, 0.54334   , 0.6870111 ],
       [0.6932374 , 0.5561742 , 0.52339315, 0.53264505, 0.4427836 ,
        0.70779717, 0.5154819 , 0.43417913, 0.68964875, 0.73049724],
       [0.42443728, 0.5373003 , 0.54822373, 0.38198662, 0.58811426,
        0.45866436, 0.5862957 , 0.47505438, 0.6054923 , 0.62915015],
       [0.56757605, 0.4031981 , 0.45900154, 0.44116735, 0.55136645,
        0.6210511 , 0.50908   , 0.5479742 , 0.74136686, 0.67689455]],
      dtype=float32)>

In [0]:
w1=tf.Variable(initializer([10,3]))
w1

<tf.Variable 'Variable:0' shape=(10, 3) dtype=float32, numpy=
array([[ 0.55423176, -0.19934082, -0.31787127],
       [ 0.62764204, -0.12228858,  0.08698499],
       [-0.6283859 ,  0.02883744,  0.5441203 ],
       [-0.16586071,  0.14455795, -0.05894995],
       [ 0.15404409, -0.5129737 , -0.13566566],
       [-0.00414991,  0.02844208, -0.52113706],
       [ 0.27885348,  0.214549  ,  0.6529777 ],
       [-0.5033104 , -0.15905184, -0.38714784],
       [ 0.17016989, -0.14573503, -0.20373645],
       [-0.02280247, -0.4333477 , -0.10263455]], dtype=float32)>

In [0]:
b1=tf.Variable(initializer([3]))
b1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 0.0298996 , -0.09214282, -0.8832848 ], dtype=float32)>

In [0]:
hypothesis1=\
  tf.nn.softmax(tf.matmul(hypothesis0, w1)+b1)
hypothesis1  

<tf.Tensor: id=83, shape=(5, 3), dtype=float32, numpy=
array([[0.6185735 , 0.21281137, 0.16861513],
       [0.6455093 , 0.19908749, 0.15540326],
       [0.6786737 , 0.19918038, 0.122146  ],
       [0.6185735 , 0.21281137, 0.16861513],
       [0.65387934, 0.21393982, 0.13218088]], dtype=float32)>

In [0]:
cost=-tf.reduce_sum(y*tf.log(hypothesis1))/len(hypothesis1)
cost

<tf.Tensor: id=101, shape=(), dtype=float32, numpy=1.3401624>

In [0]:
optimizer=tf.train.AdamOptimizer(0.01)

In [0]:
for step in range(1001):
    with tf.GradientTape() as tape:
        hypothesis0=tf.sigmoid(tf.matmul(X,w0)+b0)
        hypothesis1=tf.nn.softmax(\
                        tf.matmul(hypothesis0,w1)+b1)
        cost=-tf.reduce_sum(y*tf.log(hypothesis1))\
              /len(hypothesis1)
        grads=tape.gradient(cost,[w0,w1,b0,b1])
        optimizer.apply_gradients(grads_and_vars=zip(grads,[w0,w1,b0,b1]))
        
        if step%100==0:
            print("="*50)
            print("step:{},cost:{}".\
                  format(step, cost.numpy()))
            print("="*50)

step:0,cost:1.3271992206573486
step:100,cost:0.4165771007537842
step:200,cost:0.06777273118495941
step:300,cost:0.024507401511073112
step:400,cost:0.01287076435983181
step:500,cost:0.008024826645851135
step:600,cost:0.00551809836179018
step:700,cost:0.004041939042508602
step:800,cost:0.003094166051596403
step:900,cost:0.0024469224736094475
step:1000,cost:0.001983917783945799


In [0]:
w0

<tf.Variable 'Variable:0' shape=(2, 10) dtype=float32, numpy=
array([[-0.8338619 , -0.09449361,  2.0556808 ,  2.9214683 , -2.7054253 ,
        -2.352651  ,  2.938779  , -0.02423707, -2.6185517 , -1.2275889 ],
       [-0.81192535, -3.4228046 ,  1.0101533 ,  3.0689402 , -3.1803608 ,
         1.8884245 ,  0.9252589 ,  3.48841   ,  3.1170719 ,  3.2456267 ]],
      dtype=float32)>

In [0]:
b0

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([ 0.32625476,  1.785252  , -0.71861714, -1.5035788 ,  1.5261784 ,
        1.0950173 , -0.9615245 , -1.7847576 ,  1.0973848 , -0.71347266],
      dtype=float32)>